ARG CONN_VERSION
FROM bscppc/conn-ubuntu-base:${CONN_VERSION} as builder
LABEL maintainer="unai.perez@bsc.es"

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

COPY . /root/framework
RUN cd /root/framework/builders && \
	apt update && \
	apt install -y uuid-runtime wget openjdk-8-jdk maven python && \
	./buildlocal -N --skip-tests

FROM ubuntu:18.04
WORKDIR /root

COPY --from=builder /opt/COMPSs /opt/COMPSs
COPY --from=builder /etc/profile.d/compss.sh /etc/profile.d/compss.sh
RUN apt update && \
    apt install -y openjdk-8-jre-headless uuid-runtime && \
    echo ". /etc/profile.d/compss.sh" >> /root/.bashrc
