ARG CONN_VERSION
FROM bscppc/conn-ubuntu-base:${CONN_VERSION} as builder
LABEL maintainer="unai.perez@bsc.es"

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

COPY . /root/framework
RUN cd /root/framework/builders && \
        apt update && \
        apt install -y uuid-runtime \
                       wget \
                       openjdk-8-jdk \
                       maven \
                       build-essential \
                       autoconf \
                       automake \
                       autotools-dev \
                       libtool \
                       python3 \
                       python3-pip \
                       python3-setuptools \
                       libboost-all-dev \
                       libxml2-dev \
                       csh && \
        python3 -m pip install wheel numpy dill guppy3 && \
        ./buildlocal -N -b -p --skip-tests

FROM ubuntu:18.04

COPY --from=builder /opt/COMPSs /opt/COMPSs
RUN apt update && \
    apt install -y openjdk-8-jre-headless uuid-runtime python3 python3-pip python3-setuptools && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    python3 -m pip install wheel numpy dill guppy3
